In [172]:
import pandas as pd
#数据加载
data=pd.read_csv('family_data.csv',index_col='family_id')#把family_id作为表格的索引
data

choice_0  choice_1  choice_2  choice_3  choice_4  choice_5  \
family_id                                                               
0                52        38        12        82        33        75   
1                26         4        82         5        11        47   
2               100        54        25        12        27        82   
3                 2        95         1        96        32         6   
4                53         1        47        93        26         3   
...             ...       ...       ...       ...       ...       ...   
4995             16         1        66        33        18        70   
4996             88        66        20        17        26        54   
4997             32        66        54        17        27        21   
4998             67        92         4        17        53        77   
4999             13        11        25        80        88        40   

           choice_6  choice_7  choice_8  choice_9  n_people  
family_id                                                    
0                64        76        10        28         4  
1                38         6        66        61         4  
2                10        89        80        33         3  
3                40        31         9        59         2  
4                46        16        42        39         4  
...             ...       ...       ...       ...       ...  
4995             56        46        86        60         4  
4996             81        91        59        48         2  
4997             74        81         3         7         6  
4998              1        12        26        70         5  
4999             96        39        18        47         4  

[5000 rows x 11 columns]

## Step2，数据预处理
* 1）计算Perference Cost矩阵 pcost_mat
* 2）计算Accounting Cost矩阵 acost_mat
* 3）计算每个家庭的人数 FAMILY_SIZE
* 4）每个家庭的倾向选择（choice_） DESIRED

In [173]:
#n代表家庭成员的个数，如果满足第chioce需求，需要的penalty
def get_penalty(n,choice):
    penalty=0
    if choice==0:
        penalty=0
    if choice==1:
        penalty=50
    if choice==2:
        penalty=50+9*n
    if choice==3:
        penalty=100+9*n
    if choice==4:
        penalty=200+9*n
    if choice==5:
        penalty=200+18*n
    if choice==6:
        penalty=300+18*n
    if choice==7:
        penalty=300+36*n
    if choice==8:
        penalty=400+36*n
    if choice==9:
        penalty=500+(36+199)*n
    if choice>9:
        penalty=500+(36+398)*n
    return penalty

In [174]:
import numpy as np

N_DAYS=100 #安排的天数
N_FAMILY=5000 #家庭的ID个数
MIN_OCCUPANCY=125#最小承载量
MAX_OCCUPANCY=300#最大承载量

#计算pcost_mat,每个家庭，在什么时候(day 0-99)访问的penalty
pcost_mat=np.full(shape=(N_FAMILY,100),fill_value=999999)
for f in range(N_FAMILY):
    #家庭成员
    f_num=data.loc[f,'n_people']
    #print(f_num)
    #对于第f个家庭，初始化pcost-other choice下的penalty
    pcost_mat[f,:]=get_penalty(f_num,10)
    #计算choice0-9的penalty
    for choice in range(10):
        temp=data.loc[f][choice]#chioce的天数
        penalty=get_penalty(f_num,choice)
        pcost_mat[f,temp-1]=penalty
pcost_mat        

array([[2236, 2236, 2236, ..., 2236, 2236, 2236],
       [2236, 2236, 2236, ..., 2236, 2236, 2236],
       [1802, 1802, 1802, ..., 1802, 1802,    0],
       ...,
       [3104, 3104,  616, ..., 3104, 3104, 3104],
       [ 390, 2670, 2670, ..., 2670, 2670, 2670],
       [2236, 2236, 2236, ..., 2236, 2236, 2236]])

In [175]:
pcost_mat.shape

(5000, 100)

In [176]:
#计算accounting penalty矩阵,从前一天的参观人数，当头的参观人数
acost_mat=np.zeros(shape=(500,500),dtype=np.float64)
for i in range(acost_mat.shape[0]):
    for j in range(acost_mat.shape[1]):
        diff=abs(i-j)
        acost_mat[i,j]=max(0,(i-125)/400* i **(0.5+diff/50.0))
acost_mat        

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [1.31354104e+28, 1.16015634e+28, 1.02468267e+28, ...,
        2.07329520e+01, 2.34740633e+01, 2.65775778e+01],
       [1.52288730e+28, 1.34500277e+28, 1.18789647e+28, ...,
        2.35617801e+01, 2.08095894e+01, 2.35617801e+01],
       [1.76565289e+28, 1.55934897e+28, 1.37715019e+28, ...,
        2.67784790e+01, 2.36496052e+01, 2.08863179e+01]])

In [177]:
acost_mat.shape

(500, 500)

In [178]:
FAMILY_SIZE=data['n_people'].values
FAMILY_SIZE

array([4, 4, 3, ..., 6, 5, 4])

In [179]:
#DESIERD代表每个家庭的choice-1
#pcost_mat的day是1-100对应的下标是0-99
DESIERD=data.values[:,:-1]-1
DESIERD

array([[51, 37, 11, ..., 75,  9, 27],
       [25,  3, 81, ...,  5, 65, 60],
       [99, 53, 24, ..., 88, 79, 32],
       ...,
       [31, 65, 53, ..., 80,  2,  6],
       [66, 91,  3, ..., 11, 25, 69],
       [12, 10, 24, ..., 38, 17, 46]])

## Step3，使用LP和MIP求解 规划方案
* 1）先使用LP 对绝大部分家庭进行规划
* 2）再使用MIP 对剩余家庭进行规划
* 3）汇总两边的结果 => 最终规划方案

In [180]:
#pip install -i https://pypi.tuna.tsinghua.edu.cn/simple ortools

In [181]:
%%time
from ortools.linear_solver import pywraplp
#线性规划 ,只以preference_cost为目标
def solveLP():
    #线性规划 优化器
    solver=pywraplp.Solver('AssignmentProblem',pywraplp.Solver.GLOP_LINEAR_PROGRAMMING)
    #solver=pywraplp.Solver('AssignmentProblem',pywraplp.Solver.CBC_MIXED_INTEGER_PROGRAMMING)
    x={} #family_id 在第j天是否参观
    #每一天有哪些家庭
    candidates=[[] for x in range(N_DAYS)]    
    for i in range(N_FAMILY):
        for j in DESIERD[i,:]:        
            candidates[j].append(i)
            x[i,j]=solver.BoolVar('x[%i,%i]'%(i,j))
    #每天参观的人数100个数，x[i,j] -0或1
    daily_occupancy=[solver.Sum([x[i,j]*FAMILY_SIZE[i] for i in candidates[j]]) for j in range(N_DAYS)]
    
    #每个家庭在10个choice中出现的情况
    family_presense=[solver.Sum(x[i,j] for j in DESIERD[i,:]) for i in range(N_FAMILY)]
    
    #定义目标函数 preference cost部分
    preference_cost=solver.Sum([pcost_mat[i,j] * x[i,j] for i in range(N_FAMILY) for j in DESIERD[i,:]] )
    
    #满足preference_cost最小
    solver.Minimize(preference_cost)
    
    #认为增加约束条件Constaints
    for j in range(N_DAYS-1):
        #当前天数不超过前一天+25
        solver.Add(daily_occupancy[j]-daily_occupancy[j+1]<=25)
        #solver.Add(daily_occupancy[j+1]-daily_occupancy[j]<=25)
        
        #每个家庭都在10个chioce中出现1次
    for i in range(N_FAMILY):
        solver.Add(family_presense[i]==1)
        #每天访问人数约束
    for j in range(N_DAYS):
        solver.Add(daily_occupancy[j]>=MIN_OCCUPANCY)
        solver.Add(daily_occupancy[j]<=MAX_OCCUPANCY)
    result=solver.Solve()
    
    temp=[(i,j,x[i,j].solution_value()) for i in range(N_FAMILY) for j in DESIERD[i,:] if x[i,j].solution_value()>0]
    print(solver.Objective().Value())
    #得到参观日期的安排
    df=pd.DataFrame(temp,columns=['family_id','day','result'])
    return df
result=solveLP() 

65827.15476190476
CPU times: user 19.5 s, sys: 123 ms, total: 19.6 s
Wall time: 43.7 s


In [182]:
result

family_id  day  result
0             0   51     1.0
1             1   25     1.0
2             2   99     1.0
3             3    1     1.0
4             4   52     1.0
...         ...  ...     ...
5069       4995   15     1.0
5070       4996   87     1.0
5071       4997   31     1.0
5072       4998   91     1.0
5073       4999   12     1.0

[5074 rows x 3 columns]

In [183]:
THRS=0.999 #设置阈值
assigned_df=result[result.result>THRS]#已经安排上的结果
assigned_df

family_id  day  result
0             0   51     1.0
1             1   25     1.0
2             2   99     1.0
3             3    1     1.0
4             4   52     1.0
...         ...  ...     ...
5069       4995   15     1.0
5070       4996   87     1.0
5071       4997   31     1.0
5072       4998   91     1.0
5073       4999   12     1.0

[4940 rows x 3 columns]

In [184]:
#没有安排的，不为0和1
unassigned_df=result[(result.result<THRS) & ( result.result<1-THRS ) ]
unassigned_df

family_id  day        result
264         262   31  1.381681e-14
274         270   40  5.746538e-14
941         926   17  9.608829e-15
1706       1681   32  2.085083e-14
1797       1770   44  6.205005e-14
1858       1829   78  3.692699e-15
2914       2874   84  5.495324e-16
2950       2909   42  5.416819e-15
3581       3534   12  3.574849e-15
3592       3543   33  1.295326e-14
4282       4223   47  2.072522e-14
4473       4410   37  2.192896e-14
4694       4628   20  2.260933e-15
4994       4923   10  3.076740e-14

In [185]:
#计算每天访问的人数（根据assigned_df）
assigned_df['family_size']=FAMILY_SIZE[assigned_df.family_id]
assigned_df

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


family_id  day  result  family_size
0             0   51     1.0            4
1             1   25     1.0            4
2             2   99     1.0            3
3             3    1     1.0            2
4             4   52     1.0            4
...         ...  ...     ...          ...
5069       4995   15     1.0            4
5070       4996   87     1.0            2
5071       4997   31     1.0            6
5072       4998   91     1.0            5
5073       4999   12     1.0            4

[4940 rows x 4 columns]

In [186]:
#按照day进行聚合
occupancy=assigned_df.groupby('day').family_size.sum().values
occupancy

array([295, 271, 297, 297, 269, 248, 222, 198, 196, 297, 296, 293, 268,
       246, 220, 239, 296, 285, 269, 244, 219, 186, 208, 299, 300, 296,
       271, 238, 212, 195, 295, 275, 250, 221, 195, 172, 148, 293, 271,
       247, 221, 196, 175, 149, 297, 264, 244, 222, 196, 173, 190, 281,
       256, 236, 206, 180, 159, 174, 233, 210, 186, 163, 140, 125, 115,
       223, 198, 165, 140, 125, 125, 122, 217, 195, 173, 147, 124, 122,
       119, 222, 200, 173, 138, 120, 125, 122, 241, 225, 192, 173, 150,
       125, 120, 223, 199, 173, 150, 125, 125, 125])

In [187]:
min_occupancy=np.array([max(0,MIN_OCCUPANCY-x) for x in occupancy])
min_occupancy

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 10,  0,  0,  0,
        0,  0,  0,  3,  0,  0,  0,  0,  1,  3,  6,  0,  0,  0,  0,  5,  0,
        3,  0,  0,  0,  0,  0,  0,  5,  0,  0,  0,  0,  0,  0,  0])

In [188]:
max_occupancy=np.array([MAX_OCCUPANCY -x for x in occupancy])
max_occupancy

array([  5,  29,   3,   3,  31,  52,  78, 102, 104,   3,   4,   7,  32,
        54,  80,  61,   4,  15,  31,  56,  81, 114,  92,   1,   0,   4,
        29,  62,  88, 105,   5,  25,  50,  79, 105, 128, 152,   7,  29,
        53,  79, 104, 125, 151,   3,  36,  56,  78, 104, 127, 110,  19,
        44,  64,  94, 120, 141, 126,  67,  90, 114, 137, 160, 175, 185,
        77, 102, 135, 160, 175, 175, 178,  83, 105, 127, 153, 176, 178,
       181,  78, 100, 127, 162, 180, 175, 178,  59,  75, 108, 127, 150,
       175, 180,  77, 101, 127, 150, 175, 175, 175])

In [189]:
#使用整数规划进行求解
def solveIP(families,min_occupancy,max_occupancy):
    #创建求解器
    solver=pywraplp.Solver('AssignmentProblem',pywraplp.Solver.CBC_MIXED_INTEGER_PROGRAMMING)
    #需要安排的家庭
    n_families=len(families)
    
    x={} #family_id 在第j天是否参观
    #每一天有哪些家庭
    candidates=[[] for x in range(N_DAYS)] 
    
    for i in families:
        for j in DESIERD[i,:]:        
            candidates[j].append(i)
            x[i,j]=solver.BoolVar('x[%i,%i]'%(i,j))
    
    #每天参观的人数100个数，x[i,j] -0或1
    daily_occupancy=[solver.Sum([x[i,j] * FAMILY_SIZE[i] for i in candidates[j]]) for j in range(N_DAYS)]
    
    #每个家庭在10个choice中出现的总数
    family_presense=[solver.Sum(x[i,j] for j in DESIERD[i,:]) for i in families]
    
    #定义目标函数 preference cost部分
    preference_cost=solver.Sum([pcost_mat[i,j] * x[i,j] for i in families for j in DESIERD[i,:]] )
    
    #满足preference_cost最小
    solver.Minimize(preference_cost)
        
    #每个家庭都在10个chioce中出现1次
    for i in range(n_families):
        solver.Add(family_presense[i]==1)
        
    #每天访问人数约束
    for j in range(N_DAYS):
        solver.Add(daily_occupancy[j]>=min_occupancy[j])
        solver.Add(daily_occupancy[j]<=min_occupancy[j])
    result=solver.Solve()
    
    temp=[(i,j) for i in families  for j in DESIERD[i,:] if x[i,j].solution_value()>0]
   
    #计算剩余家庭的安排
    df=pd.DataFrame(temp,columns=['family_id','day'])
    return df

In [190]:
#没有安排的familyId 统计出来
unassigned=unassigned_df.family_id.unique()
print(unassigned)
result=solveIP(unassigned,min_occupancy,max_occupancy)
result

[ 262  270  926 1681 1770 1829 2874 2909 3534 3543 4223 4410 4628 4923]


Empty DataFrame
Columns: [family_id, day]
Index: []

In [191]:
df=pd.concat((assigned_df[['family_id','day']],result)).sort_values('family_id')
df

family_id day
0            0  51
1            1  25
2            2  99
3            3   1
4            4  52
...        ...  ..
5069      4995  15
5070      4996  87
5071      4997  31
5072      4998  91
5073      4999  12

[4940 rows x 2 columns]

In [194]:
# from numba import njititit
#根据安排情况，计算这个安排的preference cost
# @njit(fastmath=True)
def pcost(prediction):
    daily_occupancy=np.zeros(N_DAYS+1,dtype=np.int64)
    penalty=0
    for (i,p) in enumerate(prediction):
        #计算家庭人数
        n=FAMILY_SIZE[i]
        #第i个家庭，p天访问时的cost
        penalty+=pcost_mat[i,p]
        #计算当头的人数
        daily_occupancy[p]+=n
    return penalty,daily_occupancy

#根据安排情况，计算安排accounting cost
# @njit(fastmath=True)
def acost(daily_occupancy):
    accounting_cost=0
    num_out_of_range=0
    daily_occupancy[-1]=daily_occupancy[-2]
    for day in range(N_DAYS):
        n_pl=daily_occupancy[day+1]
        n=daily_occupancy[day]
        #如果超过了承载范围，则设置out_of _range
        num_out_of_range+=(n>MAX_OCCUPANCY) or (n<MIN_OCCUPANCY)
        #计算accouting cost
#         print('11111',acost_mat.shape)
#         #print('22222',accounting_cost.shape)
#         print(n)
#         print(n_pl)
        accounting_cost += acost_mat[n,n_pl]
    return accounting_cost,num_out_of_range

#根据安排prediction
# @njit(fastmath=True)
def cost_function(prediction):
    #基于predicion
    penalty,daily_occupancy=pcost(prediction)#统计preference_cost和每天承载数量
    accounting_cost,num_out_of_range=acost(daily_occupancy)#根据每天承载数量，计算accounting cost
    final_score=penalty+accounting_cost+num_out_of_range*99999999
    return final_score    

prediction=df.day.values
print(cost_function(prediction))

10875827513.839005


In [217]:
def save_result(pred,filename):
    result=pd.DataFrame(range(N_FAMILY),columns=['family_id'])    
    print(result.shape)
    new_result=result.iloc[0:4940,:]#这里调试了半天，更改了维度才搞定
#     print(new_result.shape)
#     print(type(pred))
#     print(pred)
#     print(pred+1)
#     print(len(pred))
#     pred.resize(5000)
    
    new_result['assigned_day']=pred+1
    new_result.to_csv(filename,index=False)
    return result
result=save_result(prediction,'submission.csv')

(5000, 1)


/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':


## 寻找更好的替代方案

In [ ]:
def find_better(pred):
    fobs=np.argsort(FAMILY_SIZE)
    score=cost_function(pred)
    original_score=np.inf#打擂法
    print(fobs)    
    #如果找不到更新，则退出
    while score<original_score:
        original_score=score
        
        for family_id in fobs:
            for pick in range(10):
                day=DESIERD[family_id,pick]
                oldvalue=pred[family_id]
                pred[family_id]=day
                new_score=cost_function(pred)
                if new_score<score:
                    score=new_score
                else:
                    pred[family_id]=oldvalue
        print(score,end='\r')
    print(score)
new=prediction.copy()
find_better(new)

[2070 4520 4188 ... 1081 1099 3186]
